version: "3.1"
services:
  webassembly:
    build: .
    image: julie.com/webassembly:latest
    volumes:
      - ..:/opt/code/
      - ../cache/:/root/.emscripten_cache/
    ports:
      - 8080:8080
    devices:
      - /dev/video0:/dev/video0
    entrypoint:
      - /bin/bash
      - -c
      - ./docker/launch.sh
